### ISSUE TITLE
Front BUG - При включённом в настройках чекбоксе "Темная тема" главная страница окрашивается в цветовую гамму тёмной темы с подсвеченной маркером кнопкой светлой темы.

### ISSUE THREAD

**Issue by Stan-Islav** [CalendarPracticum/calendar#304]
**Предусловия:**

1. Открыть тестовый стенд MyCalenDaily -  http://mycalendaily.acceleratorpracticum.ru/
2. Зарегистрировать и/или авторизовать пользователя с обычными правами.

**Шаги воспроизведения:**

1. Нажать на аватарку в хедере.
2. В попапе "Настройки" нажать на кнопку "Профиль"
3. Поставить галку в чекбокс "Темная тема"
4. Нажать на кнопку "Изменить данные"
5. Дождаться когда пропадёт всплывающее окно "Успех. Данные успешно обновлены!" или закрыть нажатием на иконку крестик.

**Фактический результат:**

1. Главная страница имеет цветовую гамму тёмной темы с подсвеченной маркером кнопкой светлой темы (кнопка со значком "Солнце").

**Ожидаемый результат:**

1. Главная страница имеет цветовую гамму тёмной темы с подсвеченной маркером кнопкой тёмной темы (кнопка со значком "Месяц").

**Окружение:**

1. Браузер: Google Chrome Версия 114.0.5735.134 (Официальная сборка), (64 бит), разрешение экрана 1920x1080, ОС: Windows 10 Домашняя для одного языка 21H2.

2. Браузер: Яндекс.Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1536х864, ОС: Windows 7.

3. Браузер: Safari, разрешение экрана 1366х768, ОС: Mac OS 11.0

**Приложения:**

https://github.com/CalendarPracticum/calendar/assets/111457256/0fa6ee76-052b-4391-abaa-1614998b5acb

Ссылка на баг в qase.io:

**Comment by e-zybkin** [comment]
PR #317
